### ISSUE TITLE
Avancement ?

### ISSUE THREAD

**Issue by rgrunbla** [Cartographie-Wi-Fi-et-Bluetooth/meta#1]
Hello

Je remarque plusieurs éléments sur votre avancement sur le projet : 

1. il manque une personne dans l'organisation
2. Vous n'avez, il semblerait, pas commencé votre premier rendu. Il serait temps de s'y mettre !

Est-ce qu'il est possible de remédier à ces deux points dès cette semaine ?

@Blopausore @Pchambet @Gdeterline

**Comment by augustin-bresset** [comment]
On a eu des semaines rempli par la vie associative. On a commencé à se renseigner sur les fonctionnements de github, kotlin, ... On commence le rendu bientôt.
