### ISSUE TITLE
Relecture livrable I

### ISSUE THREAD

**Issue by augustin-bresset** [Cartographie-Wi-Fi-et-Bluetooth/meta#2]
Bonjour Monsieur,
Désolé de vous demandez ca si tard mais voulez-vous bien nous donner un avis sur le livrable actuel posté sur meta ?
Cordialement,

Augustin Bresset

**Comment by rgrunbla** [comment]
Bonjour,

Sans notification avec @, par exemple @Blopausore, je ne suis pas mis au courant des issues créées sur ce dépôt, je ne vois cette issue qu'aujourd'hui.

@Blopausore @Pchambet @Gdeterline :

Jusqu'à hier, il n'y avait pas de commits sur ce dépôt, ce qui veut dire que Git n'a, au fond, pas été utilisé pour collaborer à ce rapport, et que vous vous êtes probablement pris à la dernière minute. Idéalement, le rapport final aurait du avoir une première version uploadée il y a une semaine. Pandoc n'a pas été utilisé pour générer le .pdf, si je ne m'abuse (on en avait pourtant parlé, non ?).
Il manque toujours l'un des membres du projet ajouté à ce dépôt. Seul deux personnes du groupe possèdent des commits sur le dépôt.

Bref, même si le /contenu/ du rapport (que je n'ai pour l'instant pas lu) peut potentiellement faire illusion, la méthode de travail laisse pour l'instant /très fortement/ à désirer et ne correspond pas à ce qu'on attend d'un tel projet.

**Comment by augustin-bresset** [comment]
Bonjour @rgrunbla,
En effet, je ne suis pas encore très familier avec le système d'issue sur github. On n'a pas aussi le réflexe de commit/push à chaque modification du rapport et on y travaille ! Par rapport à Pandoc, j'ai essayé et le rendu ne m'a pas plus du tout, notamment au niveau des tableaux, j'ai donc employé une extension sûre vs code appelé _Markdown PDF_. On a travaillé en parallèle sur drive et c'est pourquoi @Gdeterline n'a pas eu besoin de commit sur le github, c'est une erreur, car nous sommes censés employer seulement github puisqu'il est suffisant. 
Enfin, je tiens à m'excuser au nom de cette équipe pour le retard pris et le manque de sérieux que nous faisons paraître, mais qui ne reflète pas du tout notre engouement sur ce projet.
