### ISSUE TITLE
Point d'avancement

### ISSUE THREAD

**Issue by rgrunbla** [Cartographie-Wi-Fi-et-Bluetooth/meta#3]
Bonjour @Blopausore @Pchambet @Gdeterline @ZachMarch02 

Je commence à voir certaines choses sur les dépôts gits, et vous êtes maintenant 4 sur l'organisation, c'est bien ! Je vous propose de faire un point d'avancement rapidement (~1h max), ce mois-ci, en visio ou en présentiel, à vous de me dire ce qui vous arrange.

On parlera des étapes à suivre, de votre avancement, des difficultés rencontrées…

Répondez moi avec quelques propositions d'horaires où vous êtes tous dispos, ou alors deux propositions où vous êtes disponibles 2 par 2.

Merci d'avance,
Rémy

**Comment by Gdeterline** [comment]
Bonjour @rgrunbla, 

Est-ce que mercredi à 14h30 vous irait ? De notre côté ce serait idéal.

Bien respectueusement,
Guillaume

**Comment by rgrunbla** [comment]
Bonjour @Gdeterline @Blopausore @Pchambet @ZachMarch02,

Très bien pour mercredi. Je ne sais pas encore si ça sera en présentiel ou en visio, je vous redis ça d'ici là.

**Comment by rgrunbla** [comment]
Bonjour @Gdeterline @Blopausore @Pchambet @ZachMarch02,

On sera en visio cet après-midi,

Rémy

**Comment by augustin-bresset** [comment]
Bonjour @rgrunbla ,

On vous envoi le lien pour le visio à 14h30. 

Augustin

**Comment by rgrunbla** [comment]
Bonjour,
Je n'ai toujours pas reçu le lien.

**Comment by Pchambet** [comment]
Bonjour @rgrunbla ,

Lien du visio :

https://meet.google.com/msq-gptv-wgc

**Comment by rgrunbla** [comment]
- Si vous avez des questions, utiliser le système d'issue de Github pour intéragir avec l'encadrant (moi)
- Utiliser git le plus souvent possible, avec des branches, des commits, des pushs, des pulls, bref, avoir suivi https://docs.github.com/en/get-started/quickstart/hello-world

Groupe Django : 

- Suivre le tuto sur https://docs.djangoproject.com/en/4.1/intro/tutorial01/ en entier
- Se poser la question d'utiliser https://www.django-rest-framework.org/ pour exposer des API (interfaces de programmation) à l'application
- Se poser la question d'utiliser https://docs.djangoproject.com/en/4.1/ref/contrib/gis/ pour les données (Geo Django)
- Comprendre le format des données qui sort de l'application et décider de modèles pour enregistrer les données (dans un premier temps, uniquement des mesures, la triangulation arrivera après)

Leaflet :

- Étape 1: Avoir une carte qui fonctionne (fond de carte)
- Étape 2: Savoir charger du geojson pour afficher des marqueurs
- Étape 3: Vérifier que ça scale (plusieurs milliers de marqueurs),
- Étape 4: connecter leaflet vers une API / une source de données externe en provenance de Django

Application Android :

- Hello World en kotlin / java (plutôt kotlin)
- Essayer de lancer un scan Wi-Fi:
    - Gérer et savoir demander les bonnes permissions pour faire ce scan
    - Effectuer un scan Wi-Fi et dumper les résultats en console (Log.…)
- Essayer de faire un scan bluetooth (…)
-  Essayer de communiquer en HTTTPS avec une API externe (exposée par Django par exemple)

**Comment by rgrunbla** [comment]
Et je vais ajouter un commentaire : Ce dépôt est un dépôt « meta » pour parler de l'organisation, des rendus, des problèmes que vous avez… Utilisez plutôt un dépôt spécifique pour votre code source (type django) à la manière de ce qui a été fait pour Leaflet.

**Comment by augustin-bresset** [comment]
Bonjour @rgrunbla,
Sous quelle format désirez-vous avoir le livrable ? Selon le guide un simple tag sur git suffit mais du coup que devons nous ajouter sur moodle ?

**Comment by rgrunbla** [comment]
Bonsoir,

Oui, cela convient : générez un pdf à mettre sur Moodle qui explique le contenu du rendu.

@Blopausore @Pchambet @Gdeterline @ZachMarch02
